### PR TITLE
fix: emberfall exits with code 0 even on failing tests

### LINKED ISSUE #13: emberfall exits with code 0 even on failing tests
When tests fail, emberfall exits with code 0 when it should exit non-zero. I propose that the exit code number should be the number of tests that fail

### PR DESCRIPTION
**Pull request by talentedmrjones**
## Added

.github/workflows/tests workflow which sets up and executes [BATS](https://github.com/bats-core/bats-action)
tests/cli.bats which defines BATS tests to run against the CLI binary

## Changed
- .github/workflows/pipeline to enable the new tests workflow
- internal/engine/
  - exit non zero when tests contain errors
  - convert struct tags from json to yaml
  - added follow redirect flag as bool
  - using http.Client instead of DefaultClient

closes #13

### CODE REVIEW

File: internal/engine/test.go [hunk 1]
```diff
@@ -50,10 +52,15 @@ func (t *test) report(res *http.Response) {
...
+	fmt.Printf("%s : %s %s\n", result, t.Method, t.Url)
 	if len(errors) > 0 {
 		for _, e := range errors {
 			fmt.Printf("  %s\n", e)
 		}
+		code := len(errors)
+		if code > 125 {
+			code = 125
+		}
+		os.Exit(code)
```
Comment (sbolel) [inline internal/engine/test.go:64]: Adding comments to explain the rationale behind the exit code handling would make this even better.

**Review by sbolel — APPROVED** [review]
LGTM. Left one comment about docs. Also, is there an opportunity to update the README or docs to reflect this change in logic?

File: internal/engine/test.go (hunk 1 above)
Comment (talentedmrjones) [reply internal/engine/test.go:64]: will address better documentation in future PR
